program : main.o push.o pop.o instructions.o isEmpty.o printStack.o
	gcc -o stack_make main.o push.o pop.o instructions.o isEmpty.o printStack.o
main.o : main.c
	gcc -c main.c
push.o : push.c
	gcc -c push.c
pop.o : pop.c
	gcc -c pop.c
instructions.o : instructions.c
	gcc -c instructions.c
isEmpty.o : isEmpty.c
	gcc -c isEmpty.c
printStack.o : printStack.c
	gcc -c printStack.c
