program : main.o dequeue.o enqueue.o instructions.o isEmpty.o printQueue.o
	gcc -o queue_make main.o dequeue.o enqueue.o instructions.o isEmpty.o printQueue.o
main.o : main.c
	gcc -c main.c
dequeue.o : dequeue.c
	gcc -c dequeue.c
enqueue.o : enqueue.c
	gcc -c enqueue.c
instructions.o : instructions.c
	gcc -c instructions.c
isEmpty.o : isEmpty.c
	gcc -c isEmpty.c
printQueue.o : printQueue.c
	gcc -c printQueue.c
